#include "solarprop.h"

#include "binning.h"
#include "model.h"
#include "modelfactory.h"
#include "sde.h"
#include "spectrum.h"
#include "units.h"

#include <iostream>

void bind_solarprop(py::module_& m)
{
	py::class_<Solarprop>(m, "Solarprop")
			.def(py::init<const py::dict&>())
			.def("modulate", &Solarprop::modulate)
			.def("trajectories", &Solarprop::trajectories)
			.def("endpoints", &Solarprop::endpoints)
			.def("arrows", &Solarprop::arrows)
			.def("update_parameters", &Solarprop::updateParameters)
			.def("magnetic_field", &Solarprop::magneticField)
			.def("theta_hcs", &Solarprop::thetaHCS)
			.def("print_config", &Solarprop::printConfig);
}


using namespace Units;
using namespace std::string_literals;

/**
 * Constructor, to be called from the Python side with a python-dictionary of parameters.
 *
 * @param parameters Python dictionary that contains the parameter names as keys and the
 * corresponding values of the parameters.
 *
 */
Solarprop::Solarprop(const py::dict& parameters) :
	greenMatrix()
{
	std::cout << "This is SOLARPROP version " << versionString() << std::endl;

	updateParameters(parameters);
}

Solarprop::~Solarprop() {}

/**
 * Update the parameters.
 *
 * The data files will be re-read if necessary and the Green matrix will be reset.
 *
 * \attention Parameters not contained in the input dictionary will retain their previously
 * set values.
 *
 * @param parameters Input dictionary of updated parameter values.
 */
void Solarprop::updateParameters(const py::dict& parameters)
{
	for (auto& item : parameters)
	{
		auto key = item.first.cast<std::string>();
		if (py::isinstance<py::str>(item.second))
		{
			modelInfo.storeStringOption(key, item.second.cast<std::string>());
		}
		else if (py::isinstance<py::int_>(item.second))
		{
			modelInfo.storeIntegerOption(key, item.second.cast<int>());
		}
		else if (py::isinstance<py::float_>(item.second))
		{
			modelInfo.storeFloatOption(key, item.second.cast<double>());
		}
		else
			throw std::runtime_error(std::string("Illegal type for option: ") + key);
	}
	modelInfo.readDatafiles();
	greenMatrix.reset();
	modelForMagneticField = nullptr;
}

/** Get the current software version as a string. */
std::string Solarprop::versionString()
{
	std::string v = "(void)";
#ifdef VERSION_INFO
	v = MACRO_STRINGIFY(VERSION_INFO);
#endif
	return v;
}

/**
 *  Dump configuration information.
 *
 *  This will print:
 *  - the current version,
 *  - whether OpenMP was enabled during compilation,
 *  - the list of available models, auto-generated by the ModelFactory.
 */
void Solarprop::printConfig()
{
	std::cout << "version: " << versionString() << std::endl;
#ifdef _OPENMP
	std::cout << "openmp: yes" << std::endl;
#else
	std::cout << "openmp: no" << std::endl;
#endif

	using ModelFactory = Factory<Model, const ModelInformation&>;
	std::stringstream models;
	for (size_t iModel = 0; iModel < ModelFactory::GetCount(); ++iModel)
	{
		models << ModelFactory::GetKeyByIndex(iModel) << " ";
	}
	std::cout << "models: " << models.str() << std::endl;
}

/**
 * Calculate the cosmic-ray spectrum after solar modulation for the given local interstellar spectrum (LIS).
 *
 * The energy binning used as input should not be too fine, to keep the computing time short. To avoid
 * numerical artefacts due to the finite bins, the binning is subdivided into a finer version, which is
 * then used in the calculation of the transition probability matrix. The LIS is interpolated logarithmically
 * to estimate the values at the centers of the fine bins.
 *
 * When the option \c green is used, the Green function matrix is not calculated but read from the specified
 * file, thus cutting the computation short. Of course, this only works for the same energy binning that was
 * used in the original calculation.
 *
 * Repeated calls to this function with different values of \p flux_lis are fine, and the transition
 * probability matrix will be re-used from the first call to this function. Note that this means that the results
 * will be slightly different from those that would be obtained if the new LIS had been used for the first call,
 * due to the way the smearing of particle energies within the energy bins is handled. The same values for
 * \p ekin_lis_in_GeV have to be used for all calls to this function.
 *
 * \param ekin_lis_in_GeV Vector of energy points at which the LIS is defined, in units of GeV.
 * \param flux_lis Corresponding flux values (in arbitrary units).
 *
 * \returns Flux points after solar modulation, in the same units as \p flux_lis, at the energies listed in \p ekin_lis_in_GeV.
 */
#ifdef PYTHON_BINDINGS
py::array Solarprop::modulate(const std::vector<double>& ekin_lis_in_GeV, const std::vector<double>& flux_lis)
#else
std::vector<double> Solarprop::modulate(const std::vector<double>& ekin_lis_in_GeV, const std::vector<double>& flux_lis)
#endif
{
	// set energy units
	std::vector<double> ekin = ekin_lis_in_GeV;
	std::for_each(ekin.begin(), ekin.end(), [](double& v) { v *= GeV; });

	Spectrum lis(ekin, flux_lis);

	// Add additional computed data points if necessary
	int verbosity = modelInfo.getIntegerOptionWithDefault("verbosity", 3, false);
	int extra = modelInfo.getIntegerOptionWithDefault("extraBins", 5, false);
	lis.quality(extra);

	if (verbosity >= 2)
		std::cout << "Subdivided binning using " << extra << " subdivisions per point: " << ekin.size() << " -> " << lis.getEkin().size()
			  << " bins" << std::endl;

	if (greenMatrix.empty())
	{
		if (modelInfo.hasOption("green"))
		{
			// read Green function matrix from file (stored after previous run)
			greenMatrix = GreenFunctionMatrix(modelInfo.getStringOption("green"), greenFuncBinaryMode);
		}
		else
		{
			// calculate the Green function matrix by solving the SDEs
			greenMatrix = performModulationRun(ekin, lis, modelInfo);
			modelInfo.checkForUnusedOptions();
		}
	}

	// Calculate the modulated spectrum using the Green function matrix.
	//
	// Note that we could already fix the vector of TOA energies in the constructor instead of passing it around
	// but the normal use case will be that modulate() is only called once from the python side and then the
	// interface would look awkward. Instead, we check that the energies used when filling the Green matrix are
	// identical with the current values.
	// (We should probably also check that the mass of the cosmic-ray particle is identical...)
	double particleMass = modelInfo.getParticleProperties().mass;
	auto flux = modulateSpectrum(ekin, lis, particleMass);

#ifdef PYTHON_BINDINGS
	return py::array(flux.size(), flux.data());
#else
	return flux;
#endif
}

/**
 * Generate a number of pseudo-particle %trajectories and return the list of steps.
 * @param n Number of %trajectories to generate.
 * @param ekin_in_GeV Kinetic energy for pseudo-particles, in units of GeV.
 *
 * @return A ParticleHistories object containing the intermediate steps of each pseudo-particle.
 */
ParticleHistories Solarprop::trajectories(unsigned int n, double ekin_in_GeV)
{
	double ekin = ekin_in_GeV * GeV;
	int historyLevel = 2; // store all pseudo-particle steps
	return trajectories_or_endpoints(n, ekin, historyLevel);
}

/**
 * Generate a number of pseudo-particle %trajectories and return the list of final states (end points).
 * @param n Number of %trajectories to generate.
 * @param ekin_in_GeV Kinetic energy for pseudo-particles, in units of GeV.
 *
 * @return A vector of final states (Particle objects).
 */
std::vector<Particle> Solarprop::endpoints(unsigned int n, double ekin_in_GeV)
{
	double ekin = ekin_in_GeV * GeV;
	int historyLevel = 1; // store only endpoints
	const ParticleHistories& ph = trajectories_or_endpoints(n, ekin, historyLevel);

	std::vector<Particle> v;
	v.reserve(ph.size());

	// reduce dimension of return vector: each entry in history will only have the endpoint
	for (const std::vector<Particle>& history : ph)
		if (history.size())
			v.emplace_back(history.front());
	return v;
}

/**
 * Main implementation of the calculation for trajectories() and endpoints().
 *
 * @param n Number of %trajectories or end points to generate, respectively.
 * @param ekin Kinetic energy for pseudo-particles.
 * @param historyLevel Determines the amount of information that is stored, see Density::simulate().
 *
 * @return A ParticleHistories object containing the relevant step information, depending on the value of \p historyLevel.
 */
ParticleHistories Solarprop::trajectories_or_endpoints(unsigned int n, double ekin, int historyLevel)
{
	int verbosity = modelInfo.getIntegerOptionWithDefault("verbosity", 3, false);

	const std::unique_ptr<Model> modelTemplate = modelInfo.createModel();
	int globalSeed = modelInfo.getIntegerOptionWithDefault("globalSeed", 0);

	Density d(modelTemplate.get(), modelInfo.getParticleProperties(), {ekin}, n, true);
	std::cout << std::endl;

	bool dumpIntermediateSteps = verbosity >= 5;
	bool dumpFinalSteps = verbosity >= 4;
	const ParticleHistories& h = d.simulate(dumpIntermediateSteps, dumpFinalSteps, historyLevel, globalSeed);

	modelInfo.checkForUnusedOptions();

	return h;
}

/**
 * Calculate vectors showing the contributions of the individual transport processes to the overall step of a pseudo-particle of a fixed kinetic energy, for a
 * grid of start points.
 *
 * @param range_in_AU Range of the grid in units of AU.
 * @param ekin_in_GeV Kinetic energy for the pseudo-particle in GeV.
 * @param grid_points_per_direction Number of grid points in each direction.
 * @return Vector of Arrows objects, one for each grid point. The grid point can be obtained by Arrows::getStartPosition().
 */
std::vector<Arrows> Solarprop::arrows(double range_in_AU, double ekin_in_GeV, int grid_points_per_direction)
{
	double T = ekin_in_GeV * GeV;
	double range = range_in_AU * AU;

	int globalSeed = modelInfo.getIntegerOptionWithDefault("globalSeed", 0);

	auto prop = modelInfo.getParticleProperties();

	const std::unique_ptr<Model> model = modelInfo.createModel();
	const std::unique_ptr<SDE> sde = model->createSDE(globalSeed);

	std::vector<Arrows> va;

	int particleCounter = 0;
	for (int ix = 1; ix <= grid_points_per_direction; ++ix)
	{
		for (int iz = -grid_points_per_direction; iz <= grid_points_per_direction; ++iz)
		{
			double x = double(ix) / grid_points_per_direction * range;
			double z = double(iz) / grid_points_per_direction * range;

			double r = sqrt(x * x + z * z);
			if (r > range - 0.01 * AU)
				continue;

			Particle p(prop, T, particleCounter++);
			p.setR(r);
			p.setCosTheta(z / r);
			p.setPhi(0.);
			p.setKineticEnergy(T);

			va.emplace_back(sde->calculateArrows(p));
		}
	}

	modelInfo.checkForUnusedOptions();

	return va;
}

/**
 *  Calculate the amplitude of the magnetic field at the given heliospheric spherical coordinates \f$ (r, \theta, \phi) \f$.
 *
 * \param r Radial coordinate.
 * \param theta Polar coordinate.
 * \param phi Azimuthal coordinate.
 *
 */
double Solarprop::magneticField(double r, double theta, double phi)
{
	if (!modelForMagneticField)
		modelForMagneticField = modelInfo.createModel();

	auto prop = modelInfo.getParticleProperties();
	Particle p(prop, 1.0 * GeV, 0);

	p.setR(r);
	p.setCosTheta(std::cos(theta));
	p.setPhi(phi);

	modelForMagneticField->calculate(p);
	double B = modelForMagneticField->getB(p);
	modelInfo.checkForUnusedOptions();
	return B;
}

/**
 *  Calculate the polar coordinate of the heliospheric current sheet for the given heliospheric spherical coordinates \f$ (r, \phi) \f$.
 *
 * \param r Radial coordinate.
 * \param phi Azimuthal coordinate.
 */
double Solarprop::thetaHCS(double r, double phi)
{
	if (!modelForMagneticField)
		modelForMagneticField = modelInfo.createModel();

	auto prop = modelInfo.getParticleProperties();
	Particle p(prop, 1.0 * GeV, 0);

	p.setR(r);
	p.setCosTheta(0.);
	p.setPhi(phi);

	modelForMagneticField->calculate(p);
	double thetaPrime = modelForMagneticField->getThetaPrimeHCS(p);
	modelInfo.checkForUnusedOptions();
	return thetaPrime;
}

/**
 * Modulate given local interstellar spectrum to obtain the flux at the top of the atmosphere, based on the stored Green matrix information.
 *
 * \param ekin_toa Kinetic energies at TOA.
 * \param lis Local interstellar spectrum, provided as a Spectrum object.
 * \param mass Cosmic-ray particle mass.
 *
 * \return Vector of modulated (TOA) flux values for the energies in the \p ekin_toa vector.
 */
std::vector<double> Solarprop::modulateSpectrum(const std::vector<double>& ekin_toa, const Spectrum& lis, double mass) const
{
	greenMatrix.assert_ekin_consistency(ekin_toa, lis.getEkin());

	const auto& ekin_lis = lis.getEkin();
	const auto& is_flux = lis.getFlux();
	std::vector<double> flux(ekin_toa.size(), 0.0);

	for (unsigned int i = 0; i < ekin_toa.size(); i++)
	{
		for (unsigned int j = 0; j < ekin_lis.size(); j++)
		{
			double T = ekin_lis[j];
			if (T > 0)
			{
				flux[i] += is_flux[j] * greenMatrix.probability(i, j) / squaredMomentum(T, mass);
			}
		}
	}

	// Rescale the distribution to obtain the flux Phi = p^2 * f
	for (unsigned int i = 0; i < flux.size(); i++)
	{
		flux[i] = squaredMomentum(ekin_toa[i], mass) * flux[i];
	}

	return flux;
}

/**
 * Calculate the squared momentum from kinetic energy and particle mass.
 *
 * The squared momentum is calculated from the kinetic energy \f$ T \f$ as
 * \f[
 *     p^2 = \left(\frac{T}{c}\right)^2 + 2Tm,
 * \f]
 *
 * where \f$ c \f$ is the speed of light and \f$ m \f$ is the particle mass.
 *
 * \param T Kinetic energy of a particle.
 * \param mass Cosmic-ray particle mass.
 *
 * \return Value of the squared momentum.
 */
double Solarprop::squaredMomentum(double T, double mass) const
{
	return pow(T / c, 2) + 2. * T * mass;
}


/**
 * Run the simulation to determine the Green function matrix of the problem.
 *
 * \param ekinTOA Vector of the kinetic energy values at the top of the atmosphere to be used for the modulated spectra.
 * \param LIS Local interstellar spectrum, provided as a Spectrum object.
 * \param modelInfo The %Model information.
 *
 * \returns The Green probability matrix as a GreenFunctionMatrix object.
 */
GreenFunctionMatrix Solarprop::performModulationRun(const std::vector<double>& ekinTOA, const Spectrum& LIS, const ModelInformation& modelInfo) const
{
	int verbosity = modelInfo.getIntegerOptionWithDefault("verbosity", 3, false);

	GreenFunctionMatrix green(ekinTOA, LIS.getEkin());

	ParticleProperties prop = modelInfo.getParticleProperties();
	if (verbosity > 0)
		std::cout << "Modulate cosmic rays with mass " << prop.mass / (GeV/c2) << " GeV/c2 and charge " << prop.charge << " ... " << std::endl;

	const std::unique_ptr<Model> modelTemplate = modelInfo.createModel();
	int particlesPerBin = modelInfo.getIntegerOptionWithDefault("particlesPerBin", 1000, false);

	// construct random seed: in case multiple parallel runs are used, calculate total number of particles,
	// to make sure that all seeds will be unique
	int globalSeed = modelInfo.getIntegerOptionWithDefault("globalSeed", 0, false);
	if (globalSeed < 0)
		throw std::runtime_error("Negative global seed given: "s + std::to_string(globalSeed));

	int runNumber = modelInfo.getIntegerOptionWithDefault("runNumber", 0, false);
	if (runNumber < 0)
		throw std::runtime_error("Negative run number given: "s + std::to_string(runNumber));

	// sanity check (maybe a bit paranoid)
	size_t totalNumberOfParticles = ekinTOA.size() * particlesPerBin;
	unsigned long long int finalSeed = globalSeed + (runNumber + 1) * totalNumberOfParticles;
	if (finalSeed >= std::numeric_limits<unsigned int>::max())
		throw std::runtime_error("Run number "s + std::to_string(runNumber) + " exceeds range for random seed ("s + std::to_string(finalSeed) + ")!"s);

	// construct the seed offset (particle number will be added to this)
	unsigned int seedOffset = globalSeed + runNumber * totalNumberOfParticles;

	// determine verbosity settings
	bool dumpIntermediateSteps = verbosity >= 5;
	bool dumpFinalSteps = verbosity >= 4;

	// particle energies will be smeared out to avoid numerical artefacts, calculate the necessary information
	Binning ekinBinningLIS(LIS.getEkin());
	std::vector<EnergySmearingProperties> energySmearingProps;
	for (unsigned int i = 0; i < ekinTOA.size(); ++i)
	{
		double T = ekinTOA[i];

		EnergySmearingProperties sm;
		sm.randomSeed = 999999 + globalSeed;
		unsigned int binNumberLIS = ekinBinningLIS.findBin(T);
		double binWidthLog = std::log(ekinBinningLIS.upperBinEdge(binNumberLIS)) - std::log(ekinBinningLIS.lowerBinEdge(binNumberLIS));
		double logT = std::log(T);
		sm.T_low = std::exp(logT - 0.5 * binWidthLog);
		sm.T_up = std::exp(logT + 0.5 * binWidthLog);
		sm.spectralIndex = LIS.approximateSpectralIndex(T);
		energySmearingProps.push_back(sm);
	}

	// create a collection of test particles, energy smearing will be applied in the constructor
	Density den(modelTemplate.get(), prop, particlesPerBin, energySmearingProps, verbosity >= 1);
	// track each test particle
	den.simulate(dumpIntermediateSteps, dumpFinalSteps, false, seedOffset);
	// bin the distribution of resulting energies for the current energy bin, using the ekin binning
	green.fillFromDensity(den);

	// Save Green function matrix?
	if (modelInfo.hasOption("save"))
		green.write(modelInfo.getStringOption("save"), greenFuncBinaryMode);

	return green;
}
